sudo: required
dist: trusty
language: python
matrix:
    include:
        - python: 3.5
install:
  - pip install numpy
  - sudo apt-get install python3-gdal  
  - pip install -e .[tests]

# command to run tests
script:
  - py.test tests/
