sudo: required
language: python
matrix:
    include:
        - python: 3.5

install:
  - sudo apt-get -qq update
  - sudo apt-get install libgdal-dev
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - pip install numpy
  - pip install gdal==1.10.0
  - python setup.py install
  - pip install flake8 coveralls pytest-cov

# command to run tests
script:
  - py.test --cov gimg --cov-report term-missing
  - flake8

after_success:
  - coveralls
